### ISSUE TITLE
[BUG]: broken route

### ISSUE THREAD

**Issue by mhizterkeyz** [microapidev/auth-microapi#339]
**Describe the bug**
the route says that res.status is not a function.

**To Reproduce**
1. Send a GET request to /api/v1/auth/home

**Expected behavior**
A long text of error shows up

**Comment by dave-ok** [comment]
Hi @mhizterkeyz Thanks for helping discover this. Are you willing/able to work on this issue? This is a critical bug and needs to be resolved very quickly. At least before the morning
