### ISSUE TITLE
Admin password reset (change password)

### ISSUE THREAD

**Issue by akojif** [microapidev/auth-microapi#356]
**Is your feature request related to a problem? Please describe.**

**Describe how to intend to go about adding this feature**
Describe the approach you will take in adding this feature.

**Additional context**

**Comment by akojif** [comment]
I want to work on this. Slack username : akoji_f

**Comment by ruzor** [comment]
Provide further info, use the template.

**Comment by mhizterkeyz** [comment]
You didn't add any description to this issue

**Comment by akojif** [comment]
I'd write a set of code that listens to the endpoint to change password.

**Comment by Parsepec** [comment]
I want to work on this. Slack username : @imran
I'd implement a route that enables a registered user reset his password.

**Comment by ruzor** [comment]
@Parsepec it's yours
