### ISSUE TITLE
[FEATURE]:

### ISSUE THREAD

**Issue by Alkaseem** [microapidev/auth-microapi#357]
**Describe the bug**

**To Reproduce the bug**

**Screenshots**

**How do you intend to solve this bug?**
Describe in clear and concise manner how you intend to approach fixing this bug.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Fixing register route***
**Fixing login route**
**Fixing active user route**

**Comment by ruzor** [comment]
Use the template, so i understand what it is you're trying to do

**Comment by Alkaseem** [comment]
Is the thing i already done
