### ISSUE TITLE
Register User with phone parameter in User Schema

### ISSUE THREAD

**Issue by ruzor** [microapidev/auth-microapi#361]
**Is your feature request related to a problem? Please describe.**
Phone is needed for potential OTP

**Describe how to intend to go about adding this feature**
Redefine the User Schema to accomodate the new parameters. Write tests to ensure admin user registration route works

**Additional context**
None.

**Comment by Aptcoder** [comment]
can I work on this

**Comment by ruzor** [comment]
you have till 5:40pm
