### ISSUE TITLE
Update session handling  

### ISSUE THREAD

**Issue by ruzor** [microapidev/auth-microapi#363]
**Is your feature request related to a problem? Please describe.**
The Session Management utility has no real need to be configured externally from Passport. Since some Passport strategies already manage the user session in their implementation of user authentication, I think it'll be wise to configure a passport-local strategy to follow suite and fully replace Session Management.

**Describe how to intend to go about adding this feature**
- [ ] Use the passport-local strategy to authenticate users locally
- [ ] Configure user session options argument for all passport strategies

**Additional context**
None

**Comment by dejetem** [comment]
will take this

**Comment by josefophe** [comment]
I want to work on this issue #363

**Comment by HackinwaleDev** [comment]
Is there any challenge with this issue and you need help??

**Comment by ruzor** [comment]
Issue reopened to update session handling
