### ISSUE TITLE
Refactor all current user auth routes to adminUser routes

### ISSUE THREAD

**Issue by ruzor** [microapidev/auth-microapi#364]
**Is your feature request related to a problem? Please describe.**
Api users with role admin should be authenticated via different routes to get API_KEY

**Describe how to intend to go about adding this feature**
Rename user routes to adminUser routes for easy differentiation. 

**Additional context**
none

**Comment by CeoFred** [comment]
I want to take this up

**Comment by CeoFred** [comment]
Done https://github.com/microapidev/auth-microapi/pull/384
