### ISSUE TITLE
Add validation to check role of user making http request

### ISSUE THREAD

**Issue by ruzor** [microapidev/auth-microapi#365]
**Is your feature request related to a problem? Please describe.**
Users should be identified before allowing access to api

**Describe how to intend to go about adding this feature**
Create a middleware for routing where user authorization is needed

**Additional context**
None

**Comment by akojif** [comment]
I want to work on this

**Comment by ruzor** [comment]
Finish the first one

**Comment by dejetem** [comment]
i will take this @ruzor
