### ISSUE TITLE
Create at least 5 custom errors in the utils/error file

### ISSUE THREAD

**Issue by ruzor** [microapidev/auth-microapi#366]
**Is your feature request related to a problem? Please describe.**
Customize errors to prevent 500: Internal Server Error being returned

**Describe how to intend to go about adding this feature**
Create errors that inherit from Error object

**Additional context**
Errors will be used in response messages where they are needed e.g ValidationError, JsonWebTokenError e.t.c

**Comment by Simeon979** [comment]
I will take this @ruzor

**Comment by ruzor** [comment]
it's yours
