### ISSUE TITLE
Create and authorize guestUsers signin and signup routes such that only requests made with adminUser API_KEY passes through

### ISSUE THREAD

**Issue by ruzor** [microapidev/auth-microapi#368]
**Is your feature request related to a problem? Please describe.**
Secure routes for admin user to login and sign up users 

**Describe how to intend to go about adding this feature**
Create middleware that authorizes users before request is passed to route

**Additional context**

**Comment by CeoFred** [comment]
i'll love to work on this but the task is not all clear, could you throw more lights??

**Comment by ruzor** [comment]
are u in auth api group?

**Comment by CeoFred** [comment]
did not know that existed, can i be added??

**Comment by ruzor** [comment]
send ur slack username

**Comment by CeoFred** [comment]
@codemon

**Comment by ruzor** [comment]
There's a signin and signup route already for adminUsers. The api needs authorized routes for signin and sign up for users. Such that only an admin's API_KEY can allow users signup or signin.

**Comment by CeoFred** [comment]
If i am not mistaken you mean, to create an admin user or login an admin user, it needs an API_KEY for this?

**Comment by ruzor** [comment]
No. To create or login a guest user, an API_KEY is needed

**Comment by CeoFred** [comment]
alright, i got it.

**Comment by josefophe** [comment]
Can I also work on this ?

**Comment by Alkaseem** [comment]
signup, sign in and middleware routes already done, maybe you can only work on admin site

**Comment by CeoFred** [comment]
I don't get bro, do you mean this task has already been done???

**Comment by Alkaseem** [comment]
SignUp and signIn route is done

**Comment by ruzor** [comment]
@CeoFred these are different routes, proceed with ur work pls

**Comment by CeoFred** [comment]
https://github.com/microapidev/auth-microapi/pull/385 Done
