### ISSUE TITLE
Verify Email Upon Signup

### ISSUE THREAD

**Issue by HackinwaleDev** [microapidev/auth-microapi#371]
**Is your feature request related to a problem? Please describe.**
To confirm the person signing up is not a robot or scammer there is need to confirm the user email address before letting the person carryout core activities on the platform this API will be used.

**Describe how to intend to go about adding this feature**
The pseudocode goes thus:

- _User signed up with email and password_
- _Collect the email address of the user_
- _Write a logic that generates token and concatenate to a url_
- _Setup email protocol to transport the url to user mailbox_
- _That is all for this part_

**Additional context**
This request is 1 of 3 that will handle the email verification.
We can talk about the others later.

**Comment by ruzor** [comment]
You will also have to setup nodemailer and send html to confirm account
Will u do that at once for the complete 3 points?

**Comment by HackinwaleDev** [comment]
I will not be using NodeMailer instead SendGrid. I will do that for 3 points fine.

**Comment by ruzor** [comment]
It's yours

**Comment by HackinwaleDev** [comment]
Great.
