### ISSUE TITLE
Create a new MongoDB collection in DB whenever an admin user is registered 

### ISSUE THREAD

**Issue by ruzor** [microapidev/auth-microapi#376]
**Is your feature request related to a problem? Please describe.**
An admin user should have a specific database to work with on their registered platform.

**Describe how to intend to go about adding this feature**
Describe the approach you will take in adding this feature.

**Additional context**
A Mongo database needs to be provided for use. You'll also need to link the adminUser object schema to the created collection.

**Comment by dejetem** [comment]
i will take it

**Comment by CeoFred** [comment]
not sure why we would want to dynamically create a new collection for new admins though, i think a single user collection would be fine but incase the idea has more reasons to be implemented here is a link to whoever might want to do this https://stackoverflow.com/questions/15306916/dynamically-create-collection-with-mongoose

**Comment by ruzor** [comment]
@CeoFred I figured we could create a new collection in our databse for each adminUser, such that when that adminUser creates a guestUser with their API_KEY, that user will be stored in their created collection. Whereby the id of that collection is also linked to the adminUser through a ref.
If u think there's a better way to do it, please share with me..

**Comment by dejetem** [comment]
I will be using mongoose Dynamic Schemas package to create a collection dynamically.

**Comment by dejetem** [comment]
> **Is your feature request related to a problem? Please describe.**
> An admin user should have a specific database to work with on their registered platform.
> 
> **Describe how to intend to go about adding this feature**
> Describe the approach you will take in adding this feature.
> I will be using mongoose Dynamic Schemas package to create a collection dynamically.
> 
> **Additional context**
> A Mongo database needs to be provided for use. You'll also need to link the adminUser object schema to the created collection.
