### ISSUE TITLE
Return JWT in adminUser login response: JWT payload should include MongoDB collection URI 

### ISSUE THREAD

**Issue by ruzor** [microapidev/auth-microapi#378]
**Is your feature request related to a problem? Please describe.**
Guest users should be associated with their respective admins/platforms. 

**Describe how to intend to go about adding this feature**
This can be achieved by passing admin JWT with each guest user request.

**Additional context**

**Comment by dejetem** [comment]
i will take this

**Comment by neymarjimoh** [comment]
I can work on this

**Comment by CeoFred** [comment]
https://github.com/microapidev/auth-microapi/pull/383 Done
