### ISSUE TITLE
Implement user OAuth with facebook 

### ISSUE THREAD

**Issue by ruzor** [microapidev/auth-microapi#390]
**Is your feature request related to a problem? Please describe.**
Provide user with easier means of authentication using social auth.

**Describe how to intend to go about adding this feature**
- Use passport module or its equivalent

**Additional context**
None

**Comment by HackinwaleDev** [comment]
Kindly assign to @HopeKodi
Thank you.

**Comment by gosteve2705** [comment]
is this open?

**Comment by ruzor** [comment]
It's yours @gosteve2705

**Comment by gosteve2705** [comment]
sir after authentication ...what url is the user redirected to?

**Comment by HackinwaleDev** [comment]
Is this issue completed????????

**Comment by gosteve2705** [comment]
Submitted a pr

**Comment by HackinwaleDev** [comment]
Oh! Then link your PR to it. So it closes when it when your PR gets merged else I want it for my crush 😋
