### ISSUE TITLE
Implement user OAuth with gmail

### ISSUE THREAD

**Issue by ruzor** [microapidev/auth-microapi#391]
**Is your feature request related to a problem? Please describe.**
Provide user with easier means of authentication using social auth.

**Describe how to intend to go about adding this feature**
Use passport module or its equivalent

**Additional context**
None

**Comment by HackinwaleDev** [comment]
Kindly assign to @HopeKodi
Thank you.

**Comment by gosteve2705** [comment]
is this taken?

**Comment by Hopekodi** [comment]
Yes am on it
