### ISSUE TITLE
Implement user OAuth with Twitter

### ISSUE THREAD

**Issue by akojif** [microapidev/auth-microapi#405]
**Is your feature request related to a problem? Please describe.**

**Describe how to intend to go about adding this feature**
Describe the approach you will take in adding this feature.

**Additional context**

**Comment by CeoFred** [comment]
can i take this?

**Comment by akojif** [comment]
It has been assigned already

**Comment by CeoFred** [comment]
ok

**Comment by gosteve2705** [comment]
is @akojif still on this?

**Comment by akojif** [comment]
Nah, you can take it.

**Comment by gosteve2705** [comment]
currently waiting for my twitter developer account to be approved..if anyone has an account and can do it..please feel free to take it

**Comment by akojif** [comment]
I've a developer's account.

**Comment by gosteve2705** [comment]
Can you create an app 
Giving me the consumer I'd and key

**Comment by akojif** [comment]
Name of app?

**Comment by gosteve2705** [comment]
auth-microapi

**Comment by CeoFred** [comment]
I've got my request approved , are you already working on it?

**Comment by akojif** [comment]
You can start working on it.

**Comment by CeoFred** [comment]
https://github.com/microapidev/auth-microapi/pull/424 Done

**Comment by CeoFred** [comment]
I think I am done with this task already

**Comment by CeoFred** [comment]
https://github.com/microapidev/auth-microapi/pull/448 Done
