### ISSUE TITLE
Implement password recovery for users

### ISSUE THREAD

**Issue by ruzor** [microapidev/auth-microapi#412]
**Is your feature request related to a problem? Please describe.**

**Describe how to intend to go about adding this feature**
Describe the approach you will take in adding this feature.

**Additional context**

**Comment by neymarjimoh** [comment]
I can work on it @ruzor  
should i do it similar to the admin's password reset or this one a new password will be generated for the user for him to login with the password without needing a reset link

**Comment by ruzor** [comment]
It should be similar to admin
