### ISSUE TITLE
Ensure all endpoints have intuitive response i.e messages and status codes (both on success and on failure/error)

### ISSUE THREAD

**Issue by ruzor** [microapidev/auth-microapi#437]
**Describe the bug**
Response messaging. Use the format as described here https://docs.google.com/document/d/1YpMTCfLHFV-o9gwxovViF0GVJMHzPbhSvKGenPIEARk/edit

**To Reproduce the bug**

**Screenshots**

**How do you intend to solve this bug?**
Describe in clear and concise manner how you intend to approach fixing this bug.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by neymarjimoh** [comment]
I can do this @ruzor
