### ISSUE TITLE
Fix swagger doc with correct parameters and routes for testing

### ISSUE THREAD

**Issue by ruzor** [microapidev/auth-microapi#438]
**Describe the bug**
Unclear documentation

**To Reproduce the bug**

**Screenshots**

**How do you intend to solve this bug?**
Describe in clear and concise manner how you intend to approach fixing this bug.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by neymarjimoh** [comment]
I can work on this @ruzor

**Comment by ruzor** [comment]
it's yours

**Comment by Alkaseem** [comment]
I already do this boss
