### ISSUE TITLE
GET /api/auth/resend/verification route not working

### ISSUE THREAD

**Issue by ruzor** [microapidev/auth-microapi#439]
**Describe the bug**
Route not implemented

**To Reproduce the bug**

**Screenshots**

**How do you intend to solve this bug?**
Describe in clear and concise manner how you intend to approach fixing this bug.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by HackinwaleDev** [comment]
Hello!

This is not in anyway a bug sir. It is a feature not yet implemented in the code.
I guess it should be treated like a standalone task please kindly consider.

Thanks.

PS: After the amendment kindly assign this task to me to handle.

**Comment by ruzor** [comment]
It's yours @HackinwaleDev

**Comment by HackinwaleDev** [comment]
Ok man.
You can assign it to me. Thanks. And if possible to know the point kindly add too. Thanks again.
