### ISSUE TITLE
Total successful authentications using Twitter

### ISSUE THREAD

**Issue by ruzor** [microapidev/auth-microapi#466]
**Is your feature request related to a problem? Please describe.**

**Describe how to intend to go about adding this feature**
Describe the approach you will take in adding this feature.

**Additional context**

**Comment by CeoFred** [comment]
is this meant to be a route that returns the total number of successful auth?

**Comment by ruzor** [comment]
yes, for the last 30 days

**Comment by gosteve2705** [comment]
i think this should be an admin priviledged action...so should be implemented on tha admin route
